config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users

  resources :posts
  resources :users do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_login, only: :new
    skip_before_action :require_login, only: [:index, :show]
    def index
        @posts = Post.all
    end

    def show
    
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end

    end

    private

        def require_login
            unless user_signed_in?
                redirect_to posts_path, alert: "You need to be signed in to do this"
            end
        end

        def post_params
            params.require(:post).permit(:title, :body)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% post.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
        <% post.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/index.html.erb
<h1>Members Only Posts</h1>
<% if user_signed_in? %>
    <%= current_user.email %>
<% else %>
    <p>Not signed in</p>
<% end %>

<ul>
    <% @posts.each do |post| %>
        <li> 
           <h1> <%= post.title %> </h1>
           <div> <%= post.body %> </div>
           <% if user_signed_in? %>
                <div>Written by: <%= User.find(post.user_id).email %>
            <% else %>
                <div>Sign in to see who wrote this message</div>
           <% end %>
        </li>
    <% end %>
</ul>

<div><%= link_to "Create Post", new_post_path %></div>
<% if alert %>
    <p> <%= alert %> </p>
<% end %>
<div><%= link_to "Create Account", new_user_registration_path %></div>
<div>
    <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete } %> 
    <% else %>
        <%= link_to "Log-in", new_user_session_path %>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= render "form", post: @post %>